### ISSUE TITLE
Unable to execute: mix 

### ISSUE THREAD

**Issue by kennerleyb** [AtomBuild/atom-build-elixir#1]
Just installed Atom for the first time, trying to get it to work with Elixir. I'm using Windows 8.0 64-bit.

So, clean install, with packages "build" and "build-elixir". I make a new project for myself manually using mix, open it up in Atom, all looks good.

Then I press CTRL+ALT+B to build it and I get:

Executing: mix compile
Unable to execute: mix
Make sure cmd and cwd exists and have correct access permissions.Unable to execute: mix
Make sure cmd and cwd exists and have correct access permissions.

I can compile it manually from the command line, elixir is working fine as far as I can tell. What am I missing?

**Comment by jmerriweather** [comment]
I also have this issue

**Comment by noseglid** [comment]
It is probably not in the PATH which atom knows.

Bring up the developer tools, in the console type `process.env.PATH` press enter. Make sure `mix` is in one of those folders.

**Comment by jmerriweather** [comment]
I checked my path and it is fine. I believe the issue is that on windows we need mix.bat instead of mix.  I've cloned the repo and changed mix to mix.bat and that appears to fix the issue.

**Comment by noseglid** [comment]
That's good info.

Maybe @Gawdl3y can shed some light on this? I know he's used it successfully on windows.
