### ISSUE TITLE
Unable to get build-elixir to recognize an Elixir project

### ISSUE THREAD

**Issue by supercodepoet** [AtomBuild/atom-build-elixir#6]
I am using Atom 1.5.3 and the build plugin 0.55.0. Created a new project with `mix new` and tried to run the initial test with build. I get "No eligible build target". What am I doing wrong?

**Comment by noseglid** [comment]
You must have a file called `mix.exs` in your project root dir.

**Comment by supercodepoet** [comment]
<img width="242" alt="screen shot 2016-02-20 at 11 58 47 am" src="https://cloud.githubusercontent.com/assets/249366/13198232/56f9785e-d7c9-11e5-94f8-e3bb02d1ea65.png">

This is my directory structure. I believe I have `mix.exs` in the correct location cause `mix new` generated the structure.

**Comment by noseglid** [comment]
And do you open that folder in Atom? i.e. provide a screenshot of the atom editor's tree-view.

**Comment by supercodepoet** [comment]
<img width="1498" alt="screen shot 2016-02-20 at 1 55 01 pm" src="https://cloud.githubusercontent.com/assets/249366/13198843/91c933f6-d7d9-11e5-904b-7a0dbade7a2a.png">

**Comment by noseglid** [comment]
This is the standard setup and should work. Please verify that you have build-elixir installed and enabled. Also try and restart Atom.

**Comment by supercodepoet** [comment]
I have uninstalled/reinstalled and enabled/disabled this plugin multiple times, as well as, restarted Atom. Is there a way I can debug the loading process for this plugin to help give you any logs?

**Comment by noseglid** [comment]
You can have a look at when it asks the build providers for targets here: https://github.com/noseglid/atom-build/blob/master/lib/build.js#L177-L198

Especially when it asks `isEligible()` and subsequentially for the `settings()`.

Working well afaict at least...
![mix](https://cloud.githubusercontent.com/assets/933880/13202683/5389f006-d8a3-11e5-8669-658f511d08a5.gif)

**Comment by supercodepoet** [comment]
Refreshing the build targets got it! Thank you so much for the help.
